title = "庶民样本"
description = "EGOIST 在这里写作"
theme = "./themes/luna"
googleAnalytics = "UA-54857209-6"
url = "https://egoist.moe"
feed = true
author = "EGOIST"
email = "0x142857@gmail.com"

[themeConfig]
headerTitle = "e.z."
website = "https://github.com/egoist"
repo = "egoist/blog"
twitter = "_egoistlily"

  [[themeConfig.nav]]
  title = "about"
  link = "/about"

  [[themeConfig.nav]]
  title = "girls"
  link = "/girls"

  [[themeConfig.nav]]
  title = "donate"
  link = "/donate"

[markdown]
slugify = "limax"
highlightedLineBackground = "#ffe9ad"
hideLanguage = true

  [[markdown.plugins]]
  name = "markdown-it-footnote"
